# 운영 환경 (MySQL 사용)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/rainscene_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rainscene_user
    password: rainscene_pass
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate 모드 권장
    show-sql: false
    properties:
      hibernate:
        format_sql: true
